CREATE TABLE Users(
    ID SERIAL PRIMARY KEY,
    EmailAddress VARCHAR(255) NOT NULL UNIQUE,
    UserName VARCHAR(255) NOT NULL,
    FullUserName VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    ID_Offer INTEGER NOT NULL,
    ID_Privilege INTEGER NOT NULL
);